## Capstone project 1 ideas - Pan Chen

In [2]:
import numpy as np
import pandas as pd

### Video games and its ratings  
From https://www.kaggle.com/rush4ratio/video-game-sales-with-ratings/  

Recently I saw a study that concludes that the critic scores on Rotten Tomatoes affect a movie's box office in North America, so I was wondering if critic scores affect the sale of video games as well using this dataset downloaded from Kaggle.com. More specifically, I want to explore things like  
1. Did certain genre sell particular well, despite of critic scores?
2. Did critic scores have the same impacts on the sales of multi-platform games vs. platform-exclusive games?
3. Did critic scores from Western media have the same impacts on the sales of games in all areas in the world?
4. Are critic scores in sync with user score? Which one impact the game sales more?

With questions like these answered, game developers could decide whether or not to spend more effort to increase a game's quality and/or making better relations with reviewing websites and player community in order to get better sales.

Here is a snippet of the data set:

In [6]:
videogamedf=pd.read_csv('Video_Games_Sales_as_at_22_Dec_2016.csv')
videogamedf.head(n=15)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
5,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,NaN,NaN,NaN,NaN,NaN,NaN
6,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.28,9.14,6.50,2.88,29.80,89.0,65.0,8.5,431.0,Nintendo,E
7,Wii Play,Wii,2006.0,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92,58.0,41.0,6.6,129.0,Nintendo,E
8,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.44,6.94,4.70,2.24,28.32,87.0,80.0,8.4,594.0,Nintendo,E
9,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31,NaN,NaN,NaN,NaN,NaN,NaN
10,Nintendogs,DS,2005.0,Simulation,Nintendo,9.05,10.95,1.93,2.74,24.67,NaN,NaN,NaN,NaN,NaN,NaN
11,Mario Kart DS,DS,2005.0,Racing,Nintendo,9.71,7.47,4.13,1.90,23.21,91.0,64.0,8.6,464.0,Nintendo,E
12,Pokemon Gold/Pokemon Silver,GB,1999.0,Role-Playing,Nintendo,9.00,6.18,7.20,0.71,23.10,NaN,NaN,NaN,NaN,NaN,NaN
13,Wii Fit,Wii,2007.0,Sports,Nintendo,8.92,8.03,3.60,2.15,22.70,80.0,63.0,7.7,146.0,Nintendo,E
14,Kinect Adventures!,X360,2010.0,Misc,Microsoft Game Studios,15.00,4.89,0.24,1.69,21.81,61.0,45.0,6.3,106.0,Good Science Studio,E

### Mass Shooting in the US
From https://www.kaggle.com/zusmani/us-mass-shootings-last-50-years

Mass shootings have always been a problem that plagues America, especially with recent incidents in Las Vegas and Sutherland Springs. More specifically, I want to explore things like:
- Is there a trend in increasing of mass shooting incidents in recent years? How about increasing fatalities and injuries?
- Is there a pattern on the location of where the incident happened?
- What are some possible factors that affect the occurrences of mass shooting. (Season? Shooter's age? Shooter's employment status?)

Here is a snippet of the data set:

In [10]:
massshootingdf=pd.read_csv('Mass_Shootings_Dataset_Ver_5.csv',encoding = 'ISO-8859-1')
massshootingdf.head(n=15)

,S#,Title,Location,Date,Incident Area,Open/Close Location,Target,Cause,Summary,Fatalities,...,Total victims,Policeman Killed,Age,Employeed (Y/N),Employed at,Mental Health Issues,Race,Gender,Latitude,Longitude
0,1,Texas church mass shooting,"Sutherland Springs, TX",11/5/17,Church,Close,random,unknown,"Devin Patrick Kelley, 26, an ex-air force offi...",26,...,46,0.0,26,NaN,NaN,No,White,M,NaN,NaN
1,2,Walmart shooting in suburban Denver,"Thornton, CO",11/1/17,Wal-Mart,Open,random,unknown,"Scott Allen Ostrem, 47, walked into a Walmart ...",3,...,3,0.0,47,NaN,NaN,No,White,M,NaN,NaN
2,3,Edgewood businees park shooting,"Edgewood, MD",10/18/17,Remodeling Store,Close,coworkers,unknown,"Radee Labeeb Prince, 37, fatally shot three pe...",3,...,6,0.0,37,NaN,Advance Granite Store,No,Black,M,NaN,NaN
3,4,Las Vegas Strip mass shooting,"Las Vegas, NV",10/1/17,Las Vegas Strip Concert outside Mandala Bay,Open,random,unknown,"Stephen Craig Paddock, opened fire from the 32...",59,...,585,1.0,64,NaN,NaN,Unclear,White,M,36.181271,-115.134132
4,5,San Francisco UPS shooting,"San Francisco, CA",6/14/17,UPS facility,Close,coworkers,NaN,"Jimmy Lam, 38, fatally shot three coworkers an...",3,...,5,0.0,38,1.0,NaN,Yes,Asian,M,NaN,NaN
5,6,Pennsylvania supermarket shooting,"Tunkhannock, PA",6/7/17,Weis grocery,Close,coworkers,terrorism,"Randy Stair, a 24-year-old worker at Weis groc...",3,...,3,NaN,24,1.0,Weis grocery,Unclear,White,M,NaN,NaN
6,7,Florida awning manufacturer shooting,"Orlando, Florida",6/5/17,manufacturer Fiamma Inc.,Close,coworkers,unemployement,"John Robert Neumann, Jr., 45, a former employe...",5,...,5,NaN,45,1.0,manufacturer Fiamma Inc.,Unclear,NaN,M,NaN,NaN
7,8,Rural Ohio nursing home shooting,"Kirkersville, Ohio",5/12/17,a nursing home,Close,coworkers,NaN,"Thomas Hartless, 43, shot and killed a former ...",3,...,3,1.0,43,1.0,some nursing home,Yes,White,M,NaN,NaN
8,9,Fresno downtown shooting,"Fresno, California",4/18/17,a street in downtown,Open,random,racism,"Kori Ali Muhammad, 39, opened fire along a str...",3,...,3,NaN,39,NaN,NaN,Unclear,Black,M,NaN,NaN
9,10,Fort Lauderdale airport shooting,"Fort Lauderdale, Florida",1/6/17,baggage claim area of the airport,Close,random,terrorism,"Esteban Santiago, 26, flew from Alaska to Fort...",5,...,11,NaN,26,NaN,NaN,Yes,Latino,M,NaN,NaN
10,11,Cascade Mall shooting,"Burlington, WA",9/23/16,cosmetics section of a MacyÛªs department store,Close,women,terrorism,"Arcan Cetin, 20, killed a teen girl and three ...",5,...,5,NaN,20,NaN,NaN,Yes,NaN,M,NaN,NaN
11,12,Baton Rouge police shooting,"Baton Rouge, LA",7/17/16,NaN,Open,police,NaN,"Gavin Long, a former Marine who served in Iraq...",3,...,6,3.0,NaN,NaN,former Marine,Yes,Black,M,NaN,NaN
12,13,Dallas police shooting,"Dallas, Texas",7/7/16,at protest,Open,police,racism,"Micah Xavier Johnson, a 25-year-old Army veter...",5,...,16,5.0,25,NaN,Army veteran,Unclear,Black,M,NaN,NaN
13,14,Orlando nightclub massacre,"Orlando, Florida",6/12/16,at nightclub,Close,random,NaN,"Omar Mateen, 29, attacked the Pulse nighclub i...",49,...,102,0.0,29,NaN,NaN,Unclear,Other,M,NaN,NaN
14,15,"Ferguson, MO Drive by","Ferguson, Missouri",4/29/16,NaN,Open,random,NaN,A group of 15 to 20 people was gathered for a ...,0,...,4,0.0,0,NaN,NaN,Unknown,Unknown,Unknown,38.744217,-90.305391

### Beijing PM2.5 Data

Air pollution is becoming a serious problem in Beijing, China. With this dataset I'm trying to see things like:

- Is air quality in Beijing getting better over time?
- Is things like season/month affecting the air quality?
- Did the Olympic games in 2008 have an impact on air quality in Beijing?

Data is from https://archive.ics.uci.edu/ml/datasets/Beijing+PM2.5+Data#

Here's a sample of the data:

In [13]:
beijingdf=pd.read_csv('PRSA_data_2010.1.1-2014.12.31.csv')
beijingdf.head(n=15)

    No  year  month  day  hour  pm2.5  DEWP  TEMP    PRES cbwd    Iws  Is  Ir
0    1  2010      1    1     0    NaN   -21 -11.0  1021.0   NW   1.79   0   0
1    2  2010      1    1     1    NaN   -21 -12.0  1020.0   NW   4.92   0   0
2    3  2010      1    1     2    NaN   -21 -11.0  1019.0   NW   6.71   0   0
3    4  2010      1    1     3    NaN   -21 -14.0  1019.0   NW   9.84   0   0
4    5  2010      1    1     4    NaN   -20 -12.0  1018.0   NW  12.97   0   0
5    6  2010      1    1     5    NaN   -19 -10.0  1017.0   NW  16.10   0   0
6    7  2010      1    1     6    NaN   -19  -9.0  1017.0   NW  19.23   0   0
7    8  2010      1    1     7    NaN   -19  -9.0  1017.0   NW  21.02   0   0
8    9  2010      1    1     8    NaN   -19  -9.0  1017.0   NW  24.15   0   0
9   10  2010      1    1     9    NaN   -20  -8.0  1017.0   NW  27.28   0   0
10  11  2010      1    1    10    NaN   -19  -7.0  1017.0   NW  31.30   0   0
11  12  2010      1    1    11    NaN   -18  -5.0  1017.0   NW  34.43   0   0
12  13  2010      1    1    12    NaN   -19  -5.0  1015.0   NW  37.56   0   0
13  14  2010      1    1    13    NaN   -18  -3.0  1015.0   NW  40.69   0   0
14  15  2010      1    1    14    NaN   -18  -2.0  1014.0   NW  43.82   0   0